'use client';
import Header from "@/components/Header/index";
import "./globals.scss";
import Footer from "@/components/Footer";
import { Provider } from 'react-redux';
import store from '../components/store';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}